# 🧪 Week 1 - Lab Task: Working with DataFrames and Arrays #

**🎯 Objective**

Explore and manipulate data by using Pandas and NumPy.
**Tawshif AL Mehrab**

### Dataset ###
Use the Titanic dataset, available from the official Pandas documentation repository.

🔗 Dataset URL:
https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv

📥 Instruction:
Load the dataset directly into a DataFrame from the URL:

In [24]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")

### **Part 1: Data Exploration** ###
1. Print the shape and column names of the dataset.

2. Display basic information and summary statistics about the dataset.

3. Show the first 10 rows.

### Explaination ###
1. The `shape` attribute returns the number of rows and columns in dataset

2. The `columns` attribute returns all column names from Dataframe

In [28]:
print("Dataset Shape:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)

Dataset Shape:
(891, 12)

Column Names:
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

### info and summary ###
 -`info()` function displays information such as column , data types, and missing values
 -`describe()` function generates summary statistics for numerical columns such as mean, minimum, maximum, and standard deviation

In [83]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PassengerId          891 non-null    int64
 1   Survived             891 non-null    int64
 2   Pclass               891 non-null    int64
 3   Name                 891 non-null    str
 4   Sex                  891 non-null    str
 5   Age                  714 non-null    float64
 6   SibSp                891 non-null    int64
 7   Parch                891 non-null    int64
 8   Ticket               891 non-null    str
 9   Fare                 891 non-null    float64
 10  Cabin                204 non-null    str
 11  Embarked             889 non-null    str
 12  Fare_Euro            891 non-null    float64
 13  Age_Difference       714 non-null    float64
 14  Name_Length          891 non-null    int64
 15  Fare_Age_Difference  714 non-null    float64
 16  Sex_Code             891 non-null    int64
 17  Age_Group            891 non-null    str
dtypes: float64(5), int64(7), str(6)
memory usage: 125.4 KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,7.140000e+02,891.000000,714.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,29.627871,3.821406e-15,26.716049,4.995396,0.352413
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,45.717954,1.452650e+01,9.297889,53.513869,0.477990
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.000000,-2.927912e+01,12.000000,-66.225000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,7.277568,-9.574118e+00,20.000000,-19.512525,0.000000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,13.297864,-1.699118e+00,25.000000,-10.500000,0.000000
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,28.520000,8.300882e+00,30.000000,15.478150,1.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,471.342864,5.030088e+01,82.000000,477.329200,1.000000

In [30]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### Show the first 10 rows-
 `head(10)` function displays first 10 rows of the dataset for quick inspection understanding of the data structure

### **Part 2: Indexing and Selection** ###
1. Select the names column.

2. Select multiple columns of your choice.

3. Select a single row from the dataset.

4. Select a rectangular section (subset of rows and columns).

In [62]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### Explanation
 `Name` column from the DataFrame using square bracket notation

In [63]:
df[["Name", "Age", "Sex"]]

                                                  Name   Age     Sex
0                              Braund, Mr. Owen Harris  22.0    male
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  female
2                                Heikkinen, Miss Laina  26.0  female
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  female
4                             Allen, Mr. William Henry  35.0    male
..                                                 ...   ...     ...
886                              Montvila, Rev. Juozas  27.0    male
887                        Graham, Miss Margaret Edith  19.0  female
888            Johnston, Miss Catherine Helen "Carrie"   NaN  female
889                              Behr, Mr. Karl Howell  26.0    male
890                                Dooley, Mr. Patrick  32.0    male

[891 rows x 3 columns]

### Explanation
multiple columns by passing a list of column names inside double square brackets

In [64]:
df.iloc[0]

PassengerId                                  1
Survived                                     0
Pclass                                       3
Name                   Braund, Mr. Owen Harris
Sex                                       male
Age                                       22.0
SibSp                                        1
Parch                                        0
Ticket                               A/5 21171
Fare                                      7.25
Cabin                                      NaN
Embarked                                     S
Fare_Euro                                 6.67
Age_Difference                       -7.699118
Name_Length                                 23
Fare_Age_Difference                     -14.75
Sex_Code                                     0
Age_Group                                Adult
Name: 0, dtype: object

### Explanation
 `iloc[]` function selects rows by integer position

In [65]:
df.iloc[0:5, 0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

### Explanation
rows 0 to 4 and columns 0 to 2 using integer-based indexing with `iloc[]`

### **Part 3: Filtering** ###

1. Show only the rows where the age is above 60.

2. Show rows where the fare is above 100 and the passenger was in 1st class.

3. Identify and isolate rows with missing values in the age column.

In [67]:
# Filter older than 60
df[df["Age"] > 60]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,9.660000,36.300882,21,-55.5000,0,Senior
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C,57.020864,35.300882,30,-3.0208,0,Senior
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C,31.881864,41.300882,25,-36.3458,0,Senior
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q,7.130000,40.800882,20,-62.7500,0,Senior
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S,30.820000,31.300882,25,-27.5000,0,Senior
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S,24.426000,32.300882,25,-35.4500,0,Senior
275,276,1,1,"Andrews, Miss Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,71.721636,33.300882,32,14.9583,1,Senior
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q,7.130000,35.300882,16,-57.2500,0,Senior
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S,5.738500,31.300882,25,-54.7625,0,Senior
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,241.960000,34.300882,17,199.0000,0,Senior
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S,24.426000,35.300882,25,-38.4500,0,Senior
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S,8.820500,33.300882,22,-53.4125,1,Senior
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C,45.543864,41.300882,23,-21.4958,0,Senior
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S,23.920000,34.300882,28,-38.0000,0,Senior
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S,24.426000,32.300882,18,-35.4500,0,Senior
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S,9.660000,32.300882,18,-51.5000,0,Senior
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S,29.735136,31.300882,21,-28.6792,0,Senior
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S,27.600000,50.300882,36,-50.0000,0,Senior
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S,9.660000,40.300882,27,-59.5000,0,Senior
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S,65.320000,40.300882,28,1.0000,0,Senior
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN,73.600000,32.300882,41,18.0000,1,Senior
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,7.153000,44.300882,19,-66.2250,0,Senior

### Explanation
boolean filtering to display only rows where the `Age` column is greater than 60

In [68]:
df[(df["Fare"] > 100) & (df["Pclass"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,-10.699118,30,244.0000,0,Adult
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C,134.799136,NaN,46,NaN,1,Senior
88,89,1,1,"Fortune, Miss Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,-6.699118,25,240.0000,1,Adult
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C,227.719136,-5.699118,24,223.5208,0,Adult
195,196,1,1,"Lurette, Miss Elise",female,58.00,0,0,PC 17569,146.5208,B80,C,134.799136,28.300882,19,88.5208,1,Adult
215,216,1,1,"Newell, Miss Madeleine",female,31.00,1,0,35273,113.2750,D36,C,104.213000,1.300882,22,82.2750,1,Adult
258,259,1,1,"Ward, Miss Anna",female,35.00,0,0,PC 17755,512.3292,NaN,C,471.342864,5.300882,15,477.3292,1,Adult
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S,141.185500,28.300882,45,95.4625,1,Adult
269,270,1,1,"Bissette, Miss Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S,124.782636,5.300882,21,100.6333,1,Adult
297,298,0,1,"Allison, Miss Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,139.426000,-27.699118,27,149.5500,1,Child
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C,227.719136,20.300882,47,197.5208,1,Adult
305,306,1,1,"Allison, Master Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,139.426000,-28.779118,29,150.6300,0,Child
306,307,1,1,"Fleming, Miss Margaret",female,NaN,0,0,17421,110.8833,NaN,C,102.012636,NaN,22,NaN,1,Senior
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C,100.188000,-12.699118,82,91.9000,1,Child
311,312,1,1,"Ryerson, Miss Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,241.385000,-11.699118,25,244.3750,1,Adult
318,319,1,1,"Wick, Miss Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S,151.677364,1.300882,23,133.8667,1,Adult
319,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corn...",female,40.00,1,1,16966,134.5000,E34,C,123.740000,10.300882,56,94.5000,1,Adult
325,326,1,1,"Young, Miss Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C,124.782636,6.300882,23,99.6333,1,Adult
332,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S,141.185500,8.300882,25,115.4625,0,Adult
334,335,1,1,"Frauenthal, Mrs. Henry William (Clara Heinshei...",female,NaN,1,0,PC 17611,133.6500,NaN,S,122.958000,NaN,50,NaN,1,Senior
337,338,1,1,"Burns, Miss Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C,123.740000,11.300882,30,93.5000,1,Adult
341,342,1,1,"Fortune, Miss Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S,241.960000,-5.699118,29,239.0000,1,Adult
373,374,0,1,"Ringhini, Mr. Sante",male,22.00,0,0,PC 17760,135.6333,NaN,C,124.782636,-7.699118,19,113.6333,0,Adult
377,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C,194.580000,-2.699118,25,184.5000,0,Adult
380,381,1,1,"Bidois, Miss Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C,209.323000,12.300882,20,185.5250,1,Adult
390,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S,110.400000,6.300882,26,84.0000,0,Adult
393,394,1,1,"Newell, Miss Marjorie",female,23.00,1,0,35273,113.2750,D36,C,104.213000,-6.699118,21,90.2750,1,Adult
435,436,1,1,"Carter, Miss Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S,110.400000,-15.699118,24,106.0000,1,Child
438,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S,241.960000,34.300882,17,199.0000,0,Senior
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,139.426000,-4.699118,47,126.5500,1,Adult
505,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C,100.188000,-11.699118,42,90.9000,0,Adult
527,528,0,1,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,204.036864,NaN,18,NaN,0,Senior
537,538,1,1,"LeRoy, Miss Bertha",female,30.00,0,0,PC 17761,106.4250,NaN,C,97.911000,0.300882,18,76.4250,1,Adult
544,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C,97.911000,20.300882,26,56.4250,0,Adult
550,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C,102.012636,-12.699118,27,93.8833,0,Child
557,558,0,1,"Robbins, Mr. Victor",male,NaN,0,0,PC 17757,227.5250,NaN,C,209.323000,NaN,19,NaN,0,Senior
581,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth M...",female,39.00,1,1,17421,110.8833,C68,C,102.012636,9.300882,52,71.8833,1,Adult
609,610,1,1,"Shutes, Miss Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S,141.185500,10.300882,24,113.4625,1,Adult
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C,104.213000,28.300882,26,55.2750,0,Adult
660,661,1,1,"Frauenthal, Dr. Henry William",male,50.00,2,0,PC 17611,133.6500,NaN,S,122.958000,20.300882,29,83.6500,0,Adult
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C,471.342864,6.300882,34,476.3292,0,Adult
689,690,1,1,"Madill, Miss Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S,194.430500,-14.699118,32,196.3375,1,Child
698,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C,102.012636,19.300882,24,61.8833,0,Adult
700,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,209.323000,-11.699118,49,209.5250,1,Adult
708,709,1,1,"Cleaver, Miss Alice",female,22.00,0,0,113781,151.5500,NaN,S,139.426000,-7.699118,19,129.5500,1,Adult
716,717,1,1,"Endres, Miss Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C,209.323000,8.300882,28,189.5250,1,Adult
730,731,1,1,"Allen, Miss Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,194.430500,-0.699118,28,182.3375,1,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C,471.342864,5.300882,22,477.3292,0,Adult
742,743,1,1,"Ryerson, Miss Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,241.385000,-8.699118,36,241.3750,1,Adult
763,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S,110.400000,6.300882,41,84.0000,1,Adult
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.00,0,1,24160,211.3375,B3,S,194.430500,13.300882,53,168.3375,1,Adult
802,803,1,1,"Carter, Master William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,110.400000,-18.699118,34,109.0000,0,Child
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S,151.677364,15.300882,42,119.8667,1,Adult

### Explanation
 two conditions using the `&` operator  
It selects passengers whose fare is greater than 100 and whose passenger class is 1

In [69]:
df[df["Age"].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,7.781636,NaN,16,NaN,0,Senior
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,11.960000,NaN,28,NaN,0,Senior
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,6.647000,NaN,23,NaN,1,Senior
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,6.647000,NaN,23,NaN,0,Senior
28,29,1,3,"O'Dwyer, Miss Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,7.248864,NaN,28,NaN,1,Senior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,6.650864,NaN,16,NaN,0,Senior
863,864,0,3,"Sage, Miss Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,63.986000,NaN,32,NaN,1,Senior
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,8.740000,NaN,27,NaN,0,Senior
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,7.264136,NaN,18,NaN,0,Senior
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,NaN,39,NaN,1,Senior

### Explanation
 `isnull()` function checks for missing values in the `Age` column 
 filters and displays only rows where the age value is missing

### **Part 4: Reindexing and Dropping** ###

1. Reverse the row order of the dataset.

2. Remove one column from the dataset.

3. Remove all rows with missing values in the age column.

In [70]:
df[::-1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7.130000,2.300882,19,-24.2500,0,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,27.600000,-3.699118,21,4.0000,0,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,21.574000,NaN,39,NaN,1,Senior
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,27.600000,-10.699118,27,11.0000,1,Adult
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.960000,-2.699118,21,-14.0000,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24,-26.9500,0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44,18.1000,1,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21,-18.0750,1,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51,33.2833,1,Adult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23,-14.7500,0,Adult

### Explanation
reverses the order of the rows in the DataFrame using slicing

In [71]:
# remove cabinn column
df.drop(columns=["Cabin"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,6.670000,-7.699118,23,-14.7500,0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,65.580636,8.300882,51,33.2833,1,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,7.291000,-3.699118,21,-18.0750,1,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,48.852000,5.300882,44,18.1000,1,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,7.406000,5.300882,24,-26.9500,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,11.960000,-2.699118,21,-14.0000,0,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,S,27.600000,-10.699118,27,11.0000,1,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S,21.574000,NaN,39,NaN,1,Senior
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,27.600000,-3.699118,21,4.0000,0,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,7.130000,2.300882,19,-24.2500,0,Adult

### Explanation
The `drop()` function removes the specified column from the DataFrame.  
In this example, the `Cabin` column is removed.

In [74]:
df.dropna(subset=["Age"])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,6.670000,-7.699118,23,-14.7500,0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,65.580636,8.300882,51,33.2833,1,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,7.291000,-3.699118,21,-18.0750,1,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,48.852000,5.300882,44,18.1000,1,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,7.406000,5.300882,24,-26.9500,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,26.795000,9.300882,36,-9.8750,1,Adult
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,11.960000,-2.699118,21,-14.0000,0,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,27.600000,-10.699118,27,11.0000,1,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,27.600000,-3.699118,21,4.0000,0,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,7.130000,2.300882,19,-24.2500,0,Adult

### Explanation
 `dropna()` function remov rows containing missing values
 `subset` rows with missing values in the `Age` column are removed

### **Part 5: Arithmetic and Data Alignment** ###

1. Create a new column that converts fares from USD to Euros.

2. Subtract the average age from every age value.

3. Subtract a custom array from two selected columns in the dataset.

In [75]:
# from usd to Euros
df["Fare_Euro"] = df["Fare"] * 0.92

df[["Fare", "Fare_Euro"]]

        Fare  Fare_Euro
0     7.2500   6.670000
1    71.2833  65.580636
2     7.9250   7.291000
3    53.1000  48.852000
4     8.0500   7.406000
..       ...        ...
886  13.0000  11.960000
887  30.0000  27.600000
888  23.4500  21.574000
889  30.0000  27.600000
890   7.7500   7.130000

[891 rows x 2 columns]

### Explanation
 new column called `Fare_Euro` by multiplying the `Fare` column by an exchange rate of 0.92

In [76]:
df["Age_Difference"] = df["Age"] - df["Age"].mean()

df[["Age", "Age_Difference"]]

      Age  Age_Difference
0    22.0       -7.699118
1    38.0        8.300882
2    26.0       -3.699118
3    35.0        5.300882
4    35.0        5.300882
..    ...             ...
886  27.0       -2.699118
887  19.0      -10.699118
888   NaN             NaN
889  26.0       -3.699118
890  32.0        2.300882

[891 rows x 2 columns]

### Explanation
 `mean()` function calculates the average age of all passengers
this average is then subtracted from each value in the `Age` column

In [77]:
import numpy as np
#  custom array
custom_array = np.array([1, 10])
df[["Pclass", "Fare"]] - custom_array

     Pclass     Fare
0         2  -2.7500
1         0  61.2833
2         2  -2.0750
3         0  43.1000
4         2  -1.9500
..      ...      ...
886       1   3.0000
887       0  20.0000
888       2  13.4500
889       0  20.0000
890       2  -2.2500

[891 rows x 2 columns]

### Explanation
 subtracts the values in the custom NumPy array from the selected columns.
 `1` is subtracted from `Pclass`, and `10` is subtracted from `Fare`

### **Part 6: Applying Functions** ###

1. Create a new column with the number of characters in each name.

2. Calculate the difference between fare and age for each row.

3. Round all numerical values in the dataset to one decimal place.

In [78]:
df["Name_Length"] = df["Name"].apply(len)
df[["Name", "Name_Length"]]

                                                  Name  Name_Length
0                              Braund, Mr. Owen Harris           23
1    Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                                Heikkinen, Miss Laina           21
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                             Allen, Mr. William Henry           24
..                                                 ...          ...
886                              Montvila, Rev. Juozas           21
887                        Graham, Miss Margaret Edith           27
888            Johnston, Miss Catherine Helen "Carrie"           39
889                              Behr, Mr. Karl Howell           21
890                                Dooley, Mr. Patrick           19

[891 rows x 2 columns]

### Explanation
 `apply()` function applies the `len()` function to every value in the `Name` column.  
 creates a new column containing the number of characters in each passenger name.

In [79]:
df["Fare_Age_Difference"] = df["Fare"] - df["Age"]
df[["Fare", "Age", "Fare_Age_Difference"]]

        Fare   Age  Fare_Age_Difference
0     7.2500  22.0             -14.7500
1    71.2833  38.0              33.2833
2     7.9250  26.0             -18.0750
3    53.1000  35.0              18.1000
4     8.0500  35.0             -26.9500
..       ...   ...                  ...
886  13.0000  27.0             -14.0000
887  30.0000  19.0              11.0000
888  23.4500   NaN                  NaN
889  30.0000  26.0               4.0000
890   7.7500  32.0             -24.2500

[891 rows x 3 columns]

### Explanation
subtracts the `Age` value from the `Fare` value for each row and stores the result in a new column

In [80]:
df.round(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Fare_Euro,Age_Difference,Name_Length,Fare_Age_Difference,Sex_Code,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2,NaN,S,6.7,-7.7,23,-14.8,0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.3,C85,C,65.6,8.3,51,33.3,1,Adult
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9,NaN,S,7.3,-3.7,21,-18.1,1,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,48.9,5.3,44,18.1,1,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0,NaN,S,7.4,5.3,24,-27.0,0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S,12.0,-2.7,21,-14.0,0,Adult
887,888,1,1,"Graham, Miss Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,27.6,-10.7,27,11.0,1,Adult
888,889,0,3,"Johnston, Miss Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4,NaN,S,21.6,NaN,39,NaN,1,Senior
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,27.6,-3.7,21,4.0,0,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.8,NaN,Q,7.1,2.3,19,-24.2,0,Adult

### Explanation
 `round(1)` function rounds all numerical values in DataFrame to one decimal place

### **Part 7: Mapping and Transformation** ###
1. Convert categorical values in the gender column to numeric codes.

2. Create a new column that categorizes age into groups (e.g., child, adult, senior).

In [81]:
df["Sex_Code"] = df["Sex"].map({"male": 0, "female": 1})
df[["Sex", "Sex_Code"]]

        Sex  Sex_Code
0      male         0
1    female         1
2    female         1
3    female         1
4      male         0
..      ...       ...
886    male         0
887  female         1
888  female         1
889    male         0
890    male         0

[891 rows x 2 columns]

### Explanation
 `map()` function replaces categorical gender values with numeric codes.  
example, `male` is converted to `0` and `female` is converted to `1`

In [82]:
def age_group(age):
    if age < 18:
        return "Child"
    elif age < 60:
        return "Adult"
    else:
        return "Senior"

# Create age category column
df["Age_Group"] = df["Age"].apply(age_group)

df[["Age", "Age_Group"]]

      Age Age_Group
0    22.0     Adult
1    38.0     Adult
2    26.0     Adult
3    35.0     Adult
4    35.0     Adult
..    ...       ...
886  27.0     Adult
887  19.0     Adult
888   NaN    Senior
889  26.0     Adult
890  32.0     Adult

[891 rows x 2 columns]

### Explanation
a custom function classify passengers into age groups.  
 `apply()` function applies the `age_group()` function to each value in the `Age` column.

### **Part 8** ###

In [88]:
import csv
import time
pure_data = df.to_dict(orient="records")

In [89]:
start = time.time()
python_names = []
for row in pure_data:
    python_names.append(row["Name"])
end = time.time()
print("Pure Python time:", end - start)
python_names[:10]

Pure Python time: 0.00016760826110839844

['Braund, Mr. Owen Harris',
 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
 'Heikkinen, Miss Laina',
 'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
 'Allen, Mr. William Henry',
 'Moran, Mr. James',
 'McCarthy, Mr. Timothy J',
 'Palsson, Master Gosta Leonard',
 'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
 'Nasser, Mrs. Nicholas (Adele Achem)']

### Explanation
loops through each dictionary in the dataset and appends the `Name` value into a new list

In [90]:
start = time.time()
python_age_above_60 = []
for row in pure_data:
    if row["Age"] == row["Age"]:  
        if row["Age"] > 60:
            python_age_above_60.append(row)
end = time.time()
print("Pure Python time:", end - start)
python_age_above_60[:10]

Pure Python time: 0.0006988048553466797

[{'PassengerId': 34,
  'Survived': 0,
  'Pclass': 2,
  'Name': 'Wheadon, Mr. Edward H',
  'Sex': 'male',
  'Age': 66.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'C.A. 24579',
  'Fare': 10.5,
  'Cabin': nan,
  'Embarked': 'S',
  'Fare_Euro': 9.66,
  'Age_Difference': 36.30088235294118,
  'Name_Length': 21,
  'Fare_Age_Difference': -55.5,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 55,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Ostby, Mr. Engelhart Cornelius',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 1,
  'Ticket': '113509',
  'Fare': 61.9792,
  'Cabin': 'B30',
  'Embarked': 'C',
  'Fare_Euro': 57.020864,
  'Age_Difference': 35.30088235294118,
  'Name_Length': 30,
  'Fare_Age_Difference': -3.0208000000000013,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 97,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Goldschmidt, Mr. George B',
  'Sex': 'male',
  'Age': 71.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': 'PC 17754',
  'Fare': 34.6542,
  'Cabin': 'A5',
  'Embarked': 'C',
  'Fare_Euro': 31.881864000000004,
  'Age_Difference': 41.30088235294118,
  'Name_Length': 25,
  'Fare_Age_Difference': -36.3458,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 117,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Connors, Mr. Patrick',
  'Sex': 'male',
  'Age': 70.5,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '370369',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'Fare_Euro': 7.13,
  'Age_Difference': 40.80088235294118,
  'Name_Length': 20,
  'Fare_Age_Difference': -62.75,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 171,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Van der hoef, Mr. Wyckoff',
  'Sex': 'male',
  'Age': 61.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '111240',
  'Fare': 33.5,
  'Cabin': 'B19',
  'Embarked': 'S',
  'Fare_Euro': 30.82,
  'Age_Difference': 31.30088235294118,
  'Name_Length': 25,
  'Fare_Age_Difference': -27.5,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 253,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Stead, Mr. William Thomas',
  'Sex': 'male',
  'Age': 62.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '113514',
  'Fare': 26.55,
  'Cabin': 'C87',
  'Embarked': 'S',
  'Fare_Euro': 24.426000000000002,
  'Age_Difference': 32.30088235294118,
  'Name_Length': 25,
  'Fare_Age_Difference': -35.45,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 276,
  'Survived': 1,
  'Pclass': 1,
  'Name': 'Andrews, Miss Kornelia Theodosia',
  'Sex': 'female',
  'Age': 63.0,
  'SibSp': 1,
  'Parch': 0,
  'Ticket': '13502',
  'Fare': 77.9583,
  'Cabin': 'D7',
  'Embarked': 'S',
  'Fare_Euro': 71.721636,
  'Age_Difference': 33.30088235294118,
  'Name_Length': 32,
  'Fare_Age_Difference': 14.958299999999994,
  'Sex_Code': 1,
  'Age_Group': 'Senior'},
 {'PassengerId': 281,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Duane, Mr. Frank',
  'Sex': 'male',
  'Age': 65.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '336439',
  'Fare': 7.75,
  'Cabin': nan,
  'Embarked': 'Q',
  'Fare_Euro': 7.13,
  'Age_Difference': 35.30088235294118,
  'Name_Length': 16,
  'Fare_Age_Difference': -57.25,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 327,
  'Survived': 0,
  'Pclass': 3,
  'Name': 'Nysveen, Mr. Johan Hansen',
  'Sex': 'male',
  'Age': 61.0,
  'SibSp': 0,
  'Parch': 0,
  'Ticket': '345364',
  'Fare': 6.2375,
  'Cabin': nan,
  'Embarked': 'S',
  'Fare_Euro': 5.7385,
  'Age_Difference': 31.30088235294118,
  'Name_Length': 25,
  'Fare_Age_Difference': -54.7625,
  'Sex_Code': 0,
  'Age_Group': 'Senior'},
 {'PassengerId': 439,
  'Survived': 0,
  'Pclass': 1,
  'Name': 'Fortune, Mr. Mark',
  'Sex': 'male',
  'Age': 64.0,
  'SibSp': 1,
  'Parch': 4,
  'Ticket': '19950',
  'Fare': 263.0,
  'Cabin': 'C23 C25 C27',
  'Embarked': 'S',
  'Fare_Euro': 241.96,
  'Age_Difference': 34.30088235294118,
  'Name_Length': 17,
  'Fare_Age_Difference': 199.0,
  'Sex_Code': 0,
  'Age_Group': 'Senior'}]

### Explanation
 filters passengers whose age is greater than 60 using loops and conditional statements

In [91]:
start = time.time()
python_fares_euro = []
for row in pure_data:
    fare_euro = row["Fare"] * 0.92
    python_fares_euro.append(fare_euro)
end = time.time()
print("Pure Python time:", end - start)
python_fares_euro[:10]

Pure Python time: 0.0003409385681152344

[6.67,
 65.580636,
 7.291,
 48.852000000000004,
 7.406000000000001,
 7.781636,
 47.713499999999996,
 19.389,
 10.242636000000001,
 27.665136]

### Comparison
Pandas solutions are shorter and easier to read- while the pure Python solutions require manual loops and data handling.pandas is generally more efficient for larger datasets